# Generated by Django 4.0.5 on 2022-06-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_email_validated_profile_phone_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_validated',
            field=models.BooleanField(default=False),
        ),
    ]
